dotfiles_repo: "https://github.com/rynffoll/dotfiles"
dotfiles_name: "dotfiles"
dotfiles_branch: "master"
dotfiles_dest: "{{ envy.projects_dir }}"
dotfiles_home: "{{ envy.home_dir }}"
dotfiles_files:
  - ".bashrc"
  - ".tmux.conf"
  - ".config/mpv/config"
  - ".config/gtk-3.0/gtk.css"
  - "bin"
