tap "borkdude/brew"
tap "clojure/tools"
tap "d12frosted/emacs-plus"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mvndaemon/mvnd"
brew "ansible"
brew "ansible-lint"
brew "autoconf"
brew "automake"
brew "bash-completion"
brew "node"
brew "bitwarden-cli"
brew "pkg-config"
brew "cmake"
brew "coreutils"
brew "direnv"
brew "dive"
brew "editorconfig"
brew "gcc"
brew "git"
brew "gnu-tar"
brew "gnutls"
brew "gnupg"
brew "go"
brew "gradle"
brew "grip"
brew "groovy"
brew "htop"
brew "httpie"
brew "hunspell"
brew "jq"
brew "kcat"
brew "kustomize"
brew "leiningen"
brew "libgccjit"
brew "mas"
brew "maven"
brew "mosh"
brew "ncdu"
brew "ngrep"
brew "nmap"
brew "pandoc"
brew "pinentry-mac"
brew "plantuml"
brew "rclone"
brew "ripgrep"
brew "shellcheck"
brew "speedtest-cli"
brew "telnet"
brew "texinfo"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"
brew "yamllint"
brew "yq"
brew "zplug"
brew "borkdude/brew/babashka"
brew "borkdude/brew/clj-kondo"
brew "clojure/tools/clojure"
brew "d12frosted/emacs-plus/emacs-plus@28", args: ["with-imagemagick", "with-native-comp", "with-xwidgets"]
brew "heroku/brew/heroku"
brew "mvndaemon/mvnd/mvnd"
cask "authy"
cask "coconutbattery"
cask "dbeaver-community"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-fira-mono"
cask "font-jetbrains-mono"
cask "gimp"
cask "google-chrome"
cask "iina"
cask "iterm2"
cask "jdk-mission-control"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "keka"
cask "keyboardcleantool"
cask "microsoft-auto-update"
cask "microsoft-edge"
cask "raspberry-pi-imager"
cask "rectangle"
cask "skype"
cask "slack"
cask "sloth"
cask "spotify"
cask "teamviewer"
cask "telegram"
cask "transmission"
cask "visual-studio-code"
cask "visualvm"
cask "vnc-viewer"
cask "wireshark"
cask "zoom"
cask "zulu"
cask "zulu11"
cask "zulu8"
mas "AdGuard for Safari", id: 1440147259
mas "Bitwarden", id: 1352778147
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Tailscale", id: 1475387142
mas "Vimari", id: 1480933944
mas "WireGuard", id: 1451685025
