- hosts: all
  vars:
    dotfiles_repo: "git@github.com:rynffoll/dotfiles.git"
    dotfiles_name: "dotfiles"
    dotfiles_branch: "master"
    dotfiles_dest: "~/Projects"
    dotfiles_home: "~"
    dotfiles_files:
      - ".bashrc"
      - ".tmux.conf"
      - ".config/mpv/config"
      - ".config/gtk-3.0/gtk.css"
      - "bin"
      - ".local/share/applications/emacsclient.desktop"
      - ".local/share/applications/org-protocol.desktop"
  tasks:
    - name: Clone dotfiles
      git:
        repo: "{{ dotfiles_repo }}"
        version: "{{ dotfiles_branch }}"
        dest: "{{ dotfiles_dest }}/{{ dotfiles_name }}"
        accept_hostkey: yes

    - name: Prepare dotfiles destination
      file:
        path: "{{ (dotfiles_home ~ '/' ~ item) | dirname }}"
        state: directory
      with_items: "{{ dotfiles_files }}"

    - name: Install dotfiles
      file:
        src: "{{ dotfiles_dest }}/{{ dotfiles_name }}/{{ item }}"
        dest: "{{ dotfiles_home }}/{{ item }}"
        state: link
        force: yes
      with_items: "{{ dotfiles_files }}"

    - name: Update desktop database
      shell: update-desktop-database ~/.local/share/applications/
      tags:
        - desktop
