- hosts: all
  vars:
    dotfiles_repo: "git@github.com:rynffoll/dotfiles.git"
    dotfiles_name: "dotfiles"
    dotfiles_branch: "master"
    dotfiles_dest: "~/Projects"
    dotfiles_home: "~"
    dotfiles_configs:
      - ".bashrc"
      - ".tmux.conf"
      - ".gitconfig"
      - ".config/mpv/config"
      - ".config/gtk-3.0/gtk.css"
      - "bin"
    dotfiles_desktop_files:
      - ".local/share/applications/emacsclient.desktop"
      - ".local/share/applications/org-protocol.desktop"
  tasks:
    - name: Clone dotfiles
      git:
        repo: "{{ dotfiles_repo }}"
        version: "{{ dotfiles_branch }}"
        dest: "{{ dotfiles_dest }}/{{ dotfiles_name }}"
        accept_hostkey: yes
      tags:
        - clone

    - name: Prepare dotfiles destination
      file:
        path: "{{ (dotfiles_home ~ '/' ~ item) | dirname }}"
        state: directory
      with_items: "{{ dotfiles_files }}"

    - name: Install configs
      file:
        src: "{{ dotfiles_dest }}/{{ dotfiles_name }}/{{ item }}"
        dest: "{{ dotfiles_home }}/{{ item }}"
        state: link
        force: yes
      with_items: "{{ dotfiles_configs }}"
      tags:
        - install

    - name: Install desktop files
      file:
        src: "{{ dotfiles_dest }}/{{ dotfiles_name }}/{{ item }}"
        dest: "{{ dotfiles_home }}/{{ item }}"
        state: link
        force: yes
      with_items: "{{ dotfiles_desktop_files }}"
      register: desktop_files
      tags:
        - install
        - desktop

    - name: Update desktop database
      shell: update-desktop-database ~/.local/share/applications/
      when: desktop_files.changed
      tags:
        - desktop
