- hosts: all
  vars:
    spacemacs_repo: "https://github.com/syl20bnr/spacemacs"
    spacemacs_branch: "develop"
    spacemacs_dest: "~/.emacs.d"
    spacemacs_conf_repo: "https://github.com/rynffoll/.spacemacs.d"
    spacemacs_conf_branch: "master"
    spacemacs_conf_dest: "~/.spacemacs.d"
  tasks:
    - name: Install emacs
      become: yes
      become_user: root
      become_method: sudo
      package:
        name: emacs
        state: latest
      tags:
        - emacs
        - editors

    - name: Install spacemacs
      git:
        repo: "{{ spacemacs_repo }}"
        version: "{{ spacemacs_branch }}"
        dest: "{{ spacemacs_dest }}"
      tags:
        - emacs
        - editors

    - name: Install spacemacs config
      git:
        repo: "{{ spacemacs_conf_repo }}"
        version: "{{ spacemacs_conf_branch }}"
        dest: "{{ spacemacs_conf_dest }}"
      tags:
        - emacs
        - editors
