- hosts: all
  vars:
    spacemacs_repo: "https://github.com/syl20bnr/spacemacs"
    spacemacs_branch: "develop"
    spacemacs_dest: "~/.emacs.d"
    spacemacs_conf_repo: "git@github.com:rynffoll/.spacemacs.d.git"
    spacemacs_conf_branch: "master"
    spacemacs_conf_dest: "~/.spacemacs.d"
  tasks:
    - name: Install emacs
      become: yes
      package: name=emacs state=latest
      tags:
        - packages

    - name: Install spacemacs
      git:
        repo: "{{ spacemacs_repo }}"
        version: "{{ spacemacs_branch }}"
        dest: "{{ spacemacs_dest }}"
        accept_hostkey: yes

    - name: Install spacemacs config
      git:
        repo: "{{ spacemacs_conf_repo }}"
        version: "{{ spacemacs_conf_branch }}"
        dest: "{{ spacemacs_conf_dest }}"
        accept_hostkey: yes
