- name: Install packages
  become: yes
  become_user: root
  become_method: sudo
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ os_packages }}"
  tags:
    - packages

- name: Install npm packages
  become: yes
  become_user: root
  become_method: sudo
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items: "{{ npm_packages }}"
  tags:
    - packages
    - npm
