- name: Clone dotfiles
  git:
    repo: "{{ dotfiles_repo }}"
    version: "{{ dotfiles_branch }}"
    dest: "{{ dotfiles_dest }}/{{ dotfiles_name }}"
  tags:
    - dotfiles

- name: Prepare dotfiles destination
  file:
    path: "{{ (dotfiles_home ~ '/' ~ item) | dirname }}"
    state: directory
  with_items: "{{ dotfiles_files }}"
  tags:
    - dotfiles

- name: Install dotfiles
  file:
    src: "{{ dotfiles_dest }}/{{ dotfiles_name }}/{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item }}"
    state: link
  with_items: "{{ dotfiles_files }}"
  tags:
    - dotfiles
