emacs_dist_repo: "https://github.com/hlissner/doom-emacs"
emacs_dist_branch: "develop"
emacs_dist_dest: "~/.emacs.d"
emacs_conf_repo: "git@github.com:rynffoll/.doom.d.git"
emacs_conf_branch: "master"
emacs_conf_dest: "~/.doom.d"
