#!/bin/sh

if [[ "$#" -lt 1 ]] ; then
    emacsclient -a "" -c -e \
                "(select-frame-set-input-focus (selected-frame))" \
                "(delete-other-windows)" \
                "(spacemacs/home)"
else
    emacsclient -a "" -c -e \
                "(select-frame-set-input-focus (selected-frame))" \
                "(find-file \"$1\")"
fi

