- name: Check existing JetBrains Toolbox
  stat: path="~/.local/share/applications/jetbrains-toolbox.desktop"
  register: jb_app

- name: Get link to latest version of JetBrains Toolbox
  uri:
    url: "https://data.services.jetbrains.com//products/releases?code=TBA&latest=true&type=release"
    return_content: yes
  register: jb_response
  when: jb_app.stat.exists == False

- name: Parse link and checksum for latest Jetbrains Toolbox from resposne
  set_fact:
    jb_toolbox_link: "{{ jb_response.json.TBA.0.downloads.linux.link }}"
    jb_toolbox_checksum_link: "{{ jb_response.json.TBA.0.downloads.linux.checksumLink }}"
  when: jb_app.stat.exists == False

- name: Create temp directory for installing JetBrains Toolbox
  tempfile: state=directory suffix="jetbrains-toolbox"
  register: jb_tmpdir
  when: jb_app.stat.exists == False

- name: Uncompress JetBrains Toolbox
  unarchive:
    src: "{{ jb_toolbox_link }}"
    dest: "{{ jb_tmpdir.path }}"
    remote_src: yes
  when: jb_app.stat.exists == False

- name: Install JetBrains Toolbox
  shell: "{{ jb_tmpdir.path }}/jetbrains-toolbox-*/jetbrains-toolbox &"
  when: jb_app.stat.exists == False
