- name: Save original role_path
  set_fact:
    original_role_path: "{{ role_path }}"

- name: Install Brewfile
  include_role:
    name: geerlingguy.homebrew
  vars:
    homebrew_use_brewfile: true
    homebrew_brewfile_dir: "{{ original_role_path }}/files"
    homebrew_clear_cache: true
