---
- name: Import vars
  include_vars: macos.yml

- name: Packages
  block:
    - name: Save original role_path
      set_fact:
        original_role_path: "{{ role_path }}"

    - name: Check Brewfile
      command: "brew bundle check --file={{ original_role_path }}/files/Brewfile"
      register: brew_bundle_check_output
      ignore_errors: yes

    - name: Install Brewfile
      command: "brew bundle install --file={{ original_role_path }}/files/Brewfile"
      register: brew_bundle_check_output1
      when: brew_bundle_check_output.failed

- name: Configuration
  block:
    - name: Configure defaults
      osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.name }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      with_items: "{{ defaults }}"

    - name: Download russian keyboard layout
      become: yes
      unarchive:
        src: "https://github.com/rynffoll/custom-russian-layout/tarball/master"
        dest: "/Library/Keyboard Layouts"
        remote_src: yes
        extra_opts:
          - "--strip-components=1"
        exclude:
          - "README.org"

- name: Dictionaries
  block:
    - name: Download dictionaries
      get_url:
        url: "https://raw.githubusercontent.com/LibreOffice/dictionaries/master/{{ item }}"
        dest: "~/Library/Spelling/{{ item | basename }}"
      with_items:
        - "ru_RU/ru_RU.aff"
        - "ru_RU/ru_RU.dic"
        - "en/en_US.aff"
        - "en/en_US.dic"
