- include_vars: macos.yml

- name: Packages
  block:
    - name: Save original role_path
      set_fact:
        original_role_path: "{{ role_path }}"

    - name: Install Brewfile
      include_role:
        name: geerlingguy.homebrew
      vars:
        homebrew_use_brewfile: true
        homebrew_brewfile_dir: "{{ original_role_path }}/files"
        homebrew_clear_cache: true

- name: Configuration
  block:
    - name: Configure defaults
      osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.name }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      with_items: "{{ defaults }}"

    - name: Download russian keyboard layout
      become: yes
      unarchive:
        src: "https://github.com/rynffoll/custom-russian-layout/tarball/master"
        dest: "/Library/Keyboard Layouts"
        remote_src: yes
        extra_opts:
          - "--strip-components=1"
        exclude:
          - "README.org"

- name: Dictionaries
  block:
    - name: Download dictionaries
      get_url:
        url:  "https://raw.githubusercontent.com/LibreOffice/dictionaries/master/{{ item }}"
        dest: "~/Library/Spelling/{{ item | basename }}"
      with_items:
        - "ru_RU/ru_RU.aff"
        - "ru_RU/ru_RU.dic"
        - "en/en_US.aff"
        - "en/en_US.dic"
