- include_vars: macos.yml

- name: Save original role_path
  set_fact:
    original_role_path: "{{ role_path }}"

- name: Install Brewfile
  include_role:
    name: geerlingguy.homebrew
  vars:
    homebrew_use_brewfile: true
    homebrew_brewfile_dir: "{{ original_role_path }}/files"
    homebrew_clear_cache: true

- name: Configure defaults
  osx_defaults:
    host: currentHost
    domain: "{{ item.domain }}"
    key: "{{ item.name }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  with_items: "{{ defaults }}"

- name: Download russian keyboard layout
  become: yes
  get_url:
    url: "https://raw.githubusercontent.com/rynffoll/osx-russian-keyboard/master/{{ item | urlencode }}" 
    dest: "/Library/Keyboard Layouts/{{ item }}"
  with_items:
    - Русская - BG46.icns
    - Русская - BG46.keylayout
