- name: Remove redundant packages
  become: yes
  package: name="{{ item }}" state=absent
  with_items: "{{ redundant_packages }}"

- name: Install packages
  become: yes
  package: name="{{ item }}" state=present
  with_items: "{{ system_packages }}"

- name: Install npm packages
  become: yes
  npm: name="{{ item }}" state=present global=yes
  with_items: "{{ npm_packages }}"
