- name: Get release version
  shell: rpm -E %fedora
  register: fedora_version

- name: Install base repos
  become: yes
  package: name="{{ item.url }}" state=present disable_gpg_check=yes
  with_items: "{{ base_repos }}"

- name: Install extra repos
  become: yes
  get_url: url="{{ item.url }}" dest="/etc/yum.repos.d/"
  with_items: "{{ extra_repos }}"
