- name: Change policy and state of SELinux
  become: yes
  selinux:
    state: permissive
    policy: targeted

- name: Configure LVM for SSD
  become: yes
  lineinfile:
    dest: /etc/lvm/lvm.conf
    state: present
    regexp: "^(\\s*)issue_discards = 0"
    line: "\\1issue_discards = 1"
    backrefs: yes

- name: Enable fstrim timer for SSD
  become: yes
  service:
    name: fstrim.timer
    enabled: yes
    state: started

- name: Configure dnf - fastestmirror
  become: yes
  lineinfile:
    dest: /etc/dnf/dnf.conf
    regexp: "fastestmirror="
    line: "fastestmirror=True"
