- name: Check installed VirtualBox Extension Packs
  shell: "vboxmanage list extpacks | grep Extension\\ Packs: | sed 's/Extension\\ Packs:\\ //'"
  register: vbox_extpack_exists

- name: Get VirtualBox version
  shell: vboxmanage --version | tail -1 | sed 's/r.*//'
  register: vbox_version

- name: Create temp directory for installing JetBrains Toolbox
  tempfile: state=directory suffix="vbox-extpack"
  register: vbox_extpack_tmpdir
  when: vbox_extpack_exists.stdout == "0"

- name: Download VirtualBox Extension Pack
  get_url:
    url: "http://download.virtualbox.org/virtualbox/{{ vbox_version.stdout }}/Oracle_VM_VirtualBox_Extension_Pack-{{ vbox_version.stdout }}.vbox-extpack"
    dest: "{{ vbox_extpack_tmpdir.path }}"
  when: vbox_extpack_exists.stdout == "0"

- name: Install VirtualBox Extension Pack
  shell: "virtualbox {{ vbox_extpack_tmpdir.path }}/Oracle_VM_VirtualBox_Extension_Pack-{{ vbox_version.stdout }}.vbox-extpack &"
  when: vbox_extpack_exists.stdout == "0"
