repos:
  # base
  - name: "rpmfusion-free"
    url: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm"
  - name: "rpmfusion-nonfree"
    url: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version.stdout }}.noarch.rpm"
  - name: "russianfedora-free"
    url: "http://mirror.yandex.ru/fedora/russianfedora/russianfedora/free/fedora/russianfedora-free-release-stable.noarch.rpm"
  - name: "russianfedora-nonfree"
    url: "http://mirror.yandex.ru/fedora/russianfedora/russianfedora/nonfree/fedora/russianfedora-nonfree-release-stable.noarch.rpm"
  - name: "russianfedora-fixes"
    url: "http://mirror.yandex.ru/fedora/russianfedora/russianfedora/fixes/fedora/russianfedora-fixes-release-stable.noarch.rpm"
    # extra
  - name: "skypeforlinux"
    url: "https://repo.skype.com/rpm/stable/skype-stable.repo"
  - name: "vscode"
    url: "https://github.com/rynffoll/fedora-extra-repos/raw/master/vscode.repo"
  - name: "google-chrome"
    url: "https://github.com/RussianFedora/fedora-extra-repos/raw/master/google-chrome.repo"

packages:
  - bash-completion
  - sqlite # fix dnf completion, see https://trivialfis.github.io/linux/2017/07/28/Fix-Fedora-DNF-bash-completion.html
  - vim
  - tmux
  - htop
  - curl
  - httpie
  - nodejs
  - java-1.8.0-oracle
  - java-1.8.0-oracle-devel
  - java-1.8.0-oracle-src
  - java-1.8.0-openjdk
  - java-1.8.0-openjdk-devel
  - java-1.8.0-openjdk-src
  - java-9-openjdk
  - java-9-openjdk-devel
  - java-9-openjdk-src
  - java-9-openjdk-jmods
  - docker
  - VirtualBox
  - ansible-lint
  - nmon
  - code
  - fbless
  - acpi
  - powertop
  - tlp
  - mozilla-fira-mono-fonts
  - gimp
  - google-chrome-stable
  - gnome-tweak-tool
  - gnome-shell-extension-user-theme
  - chrome-gnome-shell
  - gnome-multi-writer
  - mpv
  - gnome-mpv
  - dropbox
  - nautilus-dropbox
  - gnome-terminal-nautilus
  - gnome-sound-recorder
  - dconf-editor
  - transmission
  - remmina
  - keepassxc
  - firewall-config
  - skypeforlinux
  - telegram-desktop

gnome:
  kbd_options:
    - { key: "/org/gnome/desktop/input-sources/xkb-options", value: "['ctrl:nocaps']" }
    - { key: "/org/gnome/desktop/input-sources/per-window", value: "true" }
  term_options:
    - { key: "/org/gnome/terminal/legacy/default-show-menubar", value: "false" }
    - { key: "/org/gnome/terminal/legacy/menu-accelerator-enabled", value: "false"}
  ui_options:
    - { key: "/org/gnome/desktop/interface/show-battery-percentage", value: "true" }
    - { key: "/org/gnome/desktop/interface/clock-show-date", value: "true" }
    - { key: "/org/gnome/desktop/wm/preferences/titlebar-font", value: "'Cantarell Bold 11'" }
    - { key: "/org/gnome/desktop/interface/font-name", value: "'Cantarell 11'" }
    - { key: "/org/gnome/desktop/interface/document-font-name", value: "'Sans 11'" }
    - { key: "/org/gnome/desktop/interface/monospace-font-name", value: "'Fira Mono Medium 11'" }
    - { key: "/org/gnome/settings-daemon/plugins/xsettings/hinting", value: "'slight'" }
    - { key: "/org/gnome/settings-daemon/plugins/xsettings/antialiasing", value: "'grayscale'" }
    - { key: "/org/gnome/desktop/wm/preferences/auto-raise", value: "true" }
    - { key: "/org/gnome/desktop/wm/preferences/mouse-button-modifier", value: "'<Super>'" } # do not use <Alt>, because it conflicts with IDEA shortcuts
    - { key: "/org/gnome/desktop/wm/preferences/resize-with-right-button", value: "true" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled", value: "true" }
    - { key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature", value: "uint32 5000" }
    - { key: "/org/gnome/desktop/sound/event-sounds", value: "false" }
    - { key: "/org/gnome/desktop/wm/keybindings/begin-resize", value: "['']" }
    - { key: "/org/gnome/desktop/wm/keybindings/begin-move", value: "['']" }
    - { key: "/org/gnome/desktop/wm/keybindings/cycle-group", value: "['']" }
    - { key: "/org/gnome/desktop/wm/keybindings/cycle-group-backward", value: "['']" }
  exts_options:
    - { key: "/org/gnome/shell/window-switcher/current-workspace-only", value: "false" }
  favorite_apps: "['google-chrome.desktop', 'org.gnome.Terminal.desktop', 'emacsclient.desktop', 'jetbrains-idea-ce.desktop']"
