system_packages:
  - bash-completion
  - sqlite # fix dnf completion, see https://trivialfis.github.io/linux/2017/07/28/Fix-Fedora-DNF-bash-completion.html
  - vim
  - tmux
  - htop
  - curl
  - httpie
  - nodejs
  - java-1.8.0-oracle
  - java-1.8.0-oracle-devel
  - java-1.8.0-oracle-src
  - java-1.8.0-openjdk
  - java-1.8.0-openjdk-devel
  - java-1.8.0-openjdk-src
  - java-9-openjdk
  - java-9-openjdk-devel
  - java-9-openjdk-src
  - java-9-openjdk-jmods
  - docker
  - VirtualBox
  - ansible-lint
  - nmon
  - code
  - fbless
  - acpi
  - powertop
  - tlp
desktop_packages:
  - mozilla-fira-mono-fonts
  - gimp
  - google-chrome-stable
  - gnome-tweak-tool
  - gnome-shell-extension-user-theme
  - chrome-gnome-shell
  - gnome-multi-writer
  - mpv
  - gnome-mpv
  - dropbox
  - nautilus-dropbox
  - gnome-terminal-nautilus
  - gnome-sound-recorder
  - dconf-editor
  - transmission
  - remmina
  - keepassxc
  - firewall-config
  - skypeforlinux
  - telegram-desktop
redundant_packages:
  - libreoffice-core
  - rhythmbox
  - gnome-weather
