---
- name: Import vars
  include_vars: "{{ emacs_dist_name }}.yml"

- name: Install emacs ({{ emacs_dist_name }}) distribution
  git:
    repo: "{{ emacs_dist_repo }}"
    version: "{{ emacs_dist_branch }}"
    dest: "{{ emacs_dist_dest }}"
    update: no
    accept_hostkey: yes
  when: emacs_dist_repo is defined

- name: Install emacs ({{ emacs_dist_name }}) config
  git:
    repo: "{{ emacs_conf_repo }}"
    version: "{{ emacs_conf_branch }}"
    dest: "{{ emacs_conf_dest }}"
    update: no
    accept_hostkey: yes
  when: emacs_conf_repo is defined
